---
apiVersion: cluster.civo.crossplane.io/v1alpha1
kind: CivoKubernetes
metadata: 
  name: wolke7-nocode
spec:
  name: wolke7-nocode
  instances: 2
  size: g3.k3s.medium
  # applications: 
    # - "traefik"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
